### ISSUE TITLE
Windows 10 1607 signing issues

### ISSUE THREAD

**Issue by CMCDragonkai** [hsluoyz/npcap-package#1]
Please update this to 0.80 as the current 0.78 is not installable fully (using all the arguments) to Windows 10 due to driver signing issues.

https://github.com/nmap/npcap/releases

**Comment by hsluoyz** [comment]
OK, submitted the update package here:  https://chocolatey.org/packages/npcap/0.80, waiting for the Chocolatey moderator to approve it.
